services:
  db:
    image: mysql:latest
    container_name: mysql_nestjs_db
    restart: always
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} 
      DATABASE_NAME: ${DATABASE_NAME} 
      DATABASE_USER: ${DATABASE_USER} 
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - nestjs_network

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_nestjs
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - nestjs_network
    depends_on:
      - db

networks:
  nestjs_network:
    driver: bridge